<?php

namespace App\FakeData;

class Paises
{
  public static $paises = [
      'Alemania', 
      'Andorra', 
      'Argentina',
      'Australia', 
      'Austria',
      'Banglandes',
      'Belice',
      'Bolivia',
      'Brasil',
      'Bulgaria',
      'Canada',
      'Republica Checa',
      'Chile',
      'China',
      'Chipre',
      'Colombia',
      'Costa Rica',
      'Croacia',
      'Cuba',
      'Dinamarca',
      'Ecuador',
      'Eslovaquia',
      'España',
      'EE.UU',
      'Finlandia',
      'Francia',
      'Georgia',
      'Grecia',
      'Honduras',
      'Hungria',
      'Irlanda',
      'Islandia',
      'Italia',
      'Jamaica',
      'Japon',
      'Luxemburgo',
      'Macedonia',
      'Malta',
      'Mexico',
      'Monaco',
      'Montenegro',
      'Noruega',
      'Nueva Zelanda',
      'Paises Bajos',
      'Panamá',
      'Paraguay',
      'Perú',
      'Polonia',
      'Portugal',
      'Reino Unido',
      'Rusia',
      'Serbia',
      'Suecia',
      'Suiza',
      'Turquia',
      'Ucrania',
      'Uruguay',
      'Venezuela',
  ];
  
}